services:
  - type: web
    name: image-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /
    disk:
      name: temp-storage
      mountPath: /tmp
      sizeGB: 1